db:
  # Connection details
  host: 13.126.128.44
  port: 5432
  user: admin
  password: root@123
  name: waba 
  auto_migrate: false

jwt:
  secret: arsalan

service:
  llm:
    chat_uri: https://llm.gasha.live/api/chat